#ifndef CONFIG_H
#define CONFIG_H

#define SDL_INIT_FLAGS SDL_INIT_TIMER | SDL_INIT_AUDIO | SDL_INIT_VIDEO | SDL_INIT_EVENTS
#define IMG_INIT_FLAGS IMG_INIT_PNG

#define WINDOW_WIDTH 1080
#define WINDOW_HEIGHT 1920
#define WINDOW_TITLE "Flappy Bird"

#define WINDOW_FLAGS SDL_WINDOW_RESIZABLE
#define RENDER_FLAGS 0

#endif
