#ifndef CONFIG_H
#define CONFIG_H

// TODO: make basic game config file

#define DEBUG_ENABLED false

#define SDL_INIT_FLAGS SDL_INIT_TIMER | SDL_INIT_AUDIO | SDL_INIT_VIDEO | SDL_INIT_EVENTS
#define IMG_INIT_FLAGS IMG_INIT_PNG
#define MIX_INIT_FLAGS 0

#define MIX_CHUNCK_SIZE 2048 

#define MAIN_TEXT_SIZE 100

#define WINDOW_WIDTH 1080
#define WINDOW_HEIGHT 1920
#define WINDOW_TITLE "Flappy Bird"

#define WINDOW_FLAGS SDL_WINDOW_RESIZABLE
#define RENDER_FLAGS 0

#define BIRD_SCALE 5
#define BIRD_X_MARGIN 100
#define BIRD_GRAVITY_FORCE 3000.0f
#define BIRD_MAX_Y_VEL 3000.0f 
#define BIRD_JUMP_FORCE -1100.0f
#define BIRD_ROTATION_SPEED 15.0f
#define BIRD_ANIM_FRAMES_COUNT 3
#define BIRD_ANIM_FRAME_TIME 0.3
#define BIRD_HITBOX_INFLATE_W 6 * BIRD_SCALE
#define BIRD_HITBOX_INFLATE_H 8 * BIRD_SCALE
#define BIRD_MIN_ANGLE -25.0
#define BIRD_MAX_ANGLE 90.0
#define BIRD_HITTET_MAX_ANGLE -140.0

#define MAX_PIPES_COUNT 3
#define PIPE_SCALE 5
#define DISTANCE_BETWEEN_PIPES 500
#define PIPE_GAP 500
#define MAX_PIPE_Y_OFFSET 400

#define FOREGROUND_X_SPEED -500

#define SCORE_TEXT_Y_OFFSET 150

#define UPDATE_FPS_COUNTER_TIME 1.0

#define GAME_OVER_FADE_SPEED 300.0
#define GAME_OVER_MAX_ALPHA 200

#endif
